name: pdmorl
channels:
  - pytorch
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.10.26=h06a4308_2
  - cairo=1.16.0=hf32fb01_1
  - certifi=2021.10.8=py38h06a4308_2
  - cudatoolkit=11.0.221=h6bb024c_0
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.1=h6c09931_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.11.0=h70c0345_0
  - gettext=0.21.0=hf68c758_0
  - glib=2.69.1=h5202010_0
  - graphite2=1.3.14=h23475e2_0
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=he6710b0_3
  - intel-openmp=2019.4=243
  - jasper=2.0.14=h07fcdf6_1
  - jpeg=9d=h7f8727e_0
  - lazy-object-proxy=1.6.0=py38h27cfd23_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libglu=9.0.0=hf484d3e_1
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.15=h63c8f33_5
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtiff=4.2.0=h85742a9_0
  - libuuid=1.0.3=h7f8727e_2
  - libvpx=1.7.0=h439df22_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - lz4-c=1.9.3=h295c915_1
  - ncurses=6.3=h7f8727e_2
  - ninja=1.10.2=hff7bd54_1
  - olefile=0.46=pyhd3eb1b0_0
  - openssl=1.1.1m=h7f8727e_0
  - pcre=8.45=h295c915_0
  - pip=21.2.4=py38h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.8.11=h12debd9_0_cpython
  - readline=8.1.2=h7f8727e_1
  - setuptools=58.0.4=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.37.0=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - wrapt=1.13.3=py38h7f8727e_2
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7f8727e_4
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==1.0.0
    - ale-py==0.7.3
    - astunparse==1.6.3
    - autograd==1.3
    - cachetools==4.2.4
    - cffi==1.15.0
    - charset-normalizer==2.0.9
    - cma==2.7.0
    - cycler==0.11.0
    - cython==0.29.26
    - dataclasses==0.6
    - fasteners==0.16.3
    - filelock==3.4.0
    - flatbuffers==2.0
    - fonttools==4.28.3
    - future==0.18.2
    - gast==0.4.0
    - glfw==2.5.0
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.42.0
    - gym==0.21.0
    - h5py==3.6.0
    - idna==3.3
    - imageio==2.13.5
    - importlib-metadata==4.8.2
    - joblib==1.1.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.2
    - markdown==3.3.6
    - matplotlib==3.5.1
    - mujoco-py==2.1.2.14
    - numpy==1.22.0
    - oauthlib==3.1.1
    - onnx==1.10.2
    - onnx-tf==1.9.0
    - opencv-python==4.5.5.62
    - opt-einsum==3.3.0
    - packaging==21.3
    - pfrl==0.3.0
    - protobuf==3.19.1
    - ptan==0.7
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.21
    - pymoo==0.5.0
    - pyparsing==3.0.6
    - python-dateutil==2.8.2
    - pyyaml==6.0
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.8
    - scikit-learn==1.0.2
    - scikit-spatial==6.3.0
    - scipy==1.7.3
    - sklearn==0.0
    - tensorboard==2.8.0
    - tensorboard-plugin-wit==1.8.0
    - tensorboardx==2.4.1
    - tensorflow==2.7.0
    - tensorflow-addons==0.15.0
    - termcolor==1.1.0
    - threadpoolctl==3.0.0
    - tqdm==4.62.3
    - typeguard==2.13.3
    - typing-extensions==4.0.1
    - urllib3==1.26.7
    - werkzeug==2.0.2
